/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as orgSetupRouteRouteImport } from './routes/(org-setup)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedVoicesRouteRouteImport } from './routes/_authenticated/voices/route'
import { Route as AuthenticatedTextToSpeechRouteRouteImport } from './routes/_authenticated/text-to-speech/route'
import { Route as AuthenticatedVoicesIndexRouteImport } from './routes/_authenticated/voices/index'
import { Route as AuthenticatedTextToSpeechIndexRouteImport } from './routes/_authenticated/text-to-speech/index'
import { Route as orgSetupOrgSelectionIndexRouteImport } from './routes/(org-setup)/org-selection/index'
import { Route as ApiVoicesSplatRouteImport } from './routes/api/voices/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedTextToSpeechGenerationIdRouteImport } from './routes/_authenticated/text-to-speech/$generationId'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const orgSetupRouteRoute = orgSetupRouteRouteImport.update({
  id: '/(org-setup)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedVoicesRouteRoute =
  AuthenticatedVoicesRouteRouteImport.update({
    id: '/voices',
    path: '/voices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTextToSpeechRouteRoute =
  AuthenticatedTextToSpeechRouteRouteImport.update({
    id: '/text-to-speech',
    path: '/text-to-speech',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVoicesIndexRoute =
  AuthenticatedVoicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVoicesRouteRoute,
  } as any)
const AuthenticatedTextToSpeechIndexRoute =
  AuthenticatedTextToSpeechIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTextToSpeechRouteRoute,
  } as any)
const orgSetupOrgSelectionIndexRoute =
  orgSetupOrgSelectionIndexRouteImport.update({
    id: '/org-selection/',
    path: '/org-selection/',
    getParentRoute: () => orgSetupRouteRoute,
  } as any)
const ApiVoicesSplatRoute = ApiVoicesSplatRouteImport.update({
  id: '/api/voices/$',
  path: '/api/voices/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTextToSpeechGenerationIdRoute =
  AuthenticatedTextToSpeechGenerationIdRouteImport.update({
    id: '/$generationId',
    path: '/$generationId',
    getParentRoute: () => AuthenticatedTextToSpeechRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/success': typeof SuccessRoute
  '/text-to-speech': typeof AuthenticatedTextToSpeechRouteRouteWithChildren
  '/voices': typeof AuthenticatedVoicesRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/text-to-speech/$generationId': typeof AuthenticatedTextToSpeechGenerationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/voices/$': typeof ApiVoicesSplatRoute
  '/org-selection/': typeof orgSetupOrgSelectionIndexRoute
  '/text-to-speech/': typeof AuthenticatedTextToSpeechIndexRoute
  '/voices/': typeof AuthenticatedVoicesIndexRoute
}
export interface FileRoutesByTo {
  '/success': typeof SuccessRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/text-to-speech/$generationId': typeof AuthenticatedTextToSpeechGenerationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/voices/$': typeof ApiVoicesSplatRoute
  '/org-selection': typeof orgSetupOrgSelectionIndexRoute
  '/text-to-speech': typeof AuthenticatedTextToSpeechIndexRoute
  '/voices': typeof AuthenticatedVoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(org-setup)': typeof orgSetupRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/success': typeof SuccessRoute
  '/_authenticated/text-to-speech': typeof AuthenticatedTextToSpeechRouteRouteWithChildren
  '/_authenticated/voices': typeof AuthenticatedVoicesRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/text-to-speech/$generationId': typeof AuthenticatedTextToSpeechGenerationIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/voices/$': typeof ApiVoicesSplatRoute
  '/(org-setup)/org-selection/': typeof orgSetupOrgSelectionIndexRoute
  '/_authenticated/text-to-speech/': typeof AuthenticatedTextToSpeechIndexRoute
  '/_authenticated/voices/': typeof AuthenticatedVoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/success'
    | '/text-to-speech'
    | '/voices'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/text-to-speech/$generationId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/voices/$'
    | '/org-selection/'
    | '/text-to-speech/'
    | '/voices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/success'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/text-to-speech/$generationId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/voices/$'
    | '/org-selection'
    | '/text-to-speech'
    | '/voices'
  id:
    | '__root__'
    | '/(auth)'
    | '/(org-setup)'
    | '/_authenticated'
    | '/success'
    | '/_authenticated/text-to-speech'
    | '/_authenticated/voices'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/text-to-speech/$generationId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/api/voices/$'
    | '/(org-setup)/org-selection/'
    | '/_authenticated/text-to-speech/'
    | '/_authenticated/voices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  orgSetupRouteRoute: typeof orgSetupRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SuccessRoute: typeof SuccessRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiVoicesSplatRoute: typeof ApiVoicesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(org-setup)': {
      id: '/(org-setup)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof orgSetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/voices': {
      id: '/_authenticated/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof AuthenticatedVoicesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/text-to-speech': {
      id: '/_authenticated/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/text-to-speech'
      preLoaderRoute: typeof AuthenticatedTextToSpeechRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/voices/': {
      id: '/_authenticated/voices/'
      path: '/'
      fullPath: '/voices/'
      preLoaderRoute: typeof AuthenticatedVoicesIndexRouteImport
      parentRoute: typeof AuthenticatedVoicesRouteRoute
    }
    '/_authenticated/text-to-speech/': {
      id: '/_authenticated/text-to-speech/'
      path: '/'
      fullPath: '/text-to-speech/'
      preLoaderRoute: typeof AuthenticatedTextToSpeechIndexRouteImport
      parentRoute: typeof AuthenticatedTextToSpeechRouteRoute
    }
    '/(org-setup)/org-selection/': {
      id: '/(org-setup)/org-selection/'
      path: '/org-selection'
      fullPath: '/org-selection/'
      preLoaderRoute: typeof orgSetupOrgSelectionIndexRouteImport
      parentRoute: typeof orgSetupRouteRoute
    }
    '/api/voices/$': {
      id: '/api/voices/$'
      path: '/api/voices/$'
      fullPath: '/api/voices/$'
      preLoaderRoute: typeof ApiVoicesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/text-to-speech/$generationId': {
      id: '/_authenticated/text-to-speech/$generationId'
      path: '/$generationId'
      fullPath: '/text-to-speech/$generationId'
      preLoaderRoute: typeof AuthenticatedTextToSpeechGenerationIdRouteImport
      parentRoute: typeof AuthenticatedTextToSpeechRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface orgSetupRouteRouteChildren {
  orgSetupOrgSelectionIndexRoute: typeof orgSetupOrgSelectionIndexRoute
}

const orgSetupRouteRouteChildren: orgSetupRouteRouteChildren = {
  orgSetupOrgSelectionIndexRoute: orgSetupOrgSelectionIndexRoute,
}

const orgSetupRouteRouteWithChildren = orgSetupRouteRoute._addFileChildren(
  orgSetupRouteRouteChildren,
)

interface AuthenticatedTextToSpeechRouteRouteChildren {
  AuthenticatedTextToSpeechGenerationIdRoute: typeof AuthenticatedTextToSpeechGenerationIdRoute
  AuthenticatedTextToSpeechIndexRoute: typeof AuthenticatedTextToSpeechIndexRoute
}

const AuthenticatedTextToSpeechRouteRouteChildren: AuthenticatedTextToSpeechRouteRouteChildren =
  {
    AuthenticatedTextToSpeechGenerationIdRoute:
      AuthenticatedTextToSpeechGenerationIdRoute,
    AuthenticatedTextToSpeechIndexRoute: AuthenticatedTextToSpeechIndexRoute,
  }

const AuthenticatedTextToSpeechRouteRouteWithChildren =
  AuthenticatedTextToSpeechRouteRoute._addFileChildren(
    AuthenticatedTextToSpeechRouteRouteChildren,
  )

interface AuthenticatedVoicesRouteRouteChildren {
  AuthenticatedVoicesIndexRoute: typeof AuthenticatedVoicesIndexRoute
}

const AuthenticatedVoicesRouteRouteChildren: AuthenticatedVoicesRouteRouteChildren =
  {
    AuthenticatedVoicesIndexRoute: AuthenticatedVoicesIndexRoute,
  }

const AuthenticatedVoicesRouteRouteWithChildren =
  AuthenticatedVoicesRouteRoute._addFileChildren(
    AuthenticatedVoicesRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTextToSpeechRouteRoute: typeof AuthenticatedTextToSpeechRouteRouteWithChildren
  AuthenticatedVoicesRouteRoute: typeof AuthenticatedVoicesRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTextToSpeechRouteRoute:
    AuthenticatedTextToSpeechRouteRouteWithChildren,
  AuthenticatedVoicesRouteRoute: AuthenticatedVoicesRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  orgSetupRouteRoute: orgSetupRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SuccessRoute: SuccessRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiVoicesSplatRoute: ApiVoicesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
