/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVoicesRouteRouteImport } from './routes/dashboard/voices/route'
import { Route as DashboardTextToSpeechRouteRouteImport } from './routes/dashboard/text-to-speech/route'
import { Route as DashboardVoicesIndexRouteImport } from './routes/dashboard/voices/index'
import { Route as DashboardTextToSpeechIndexRouteImport } from './routes/dashboard/text-to-speech/index'
import { Route as DashboardTextToSpeechGenerationIdRouteImport } from './routes/dashboard/text-to-speech/$generationId'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVoicesRouteRoute = DashboardVoicesRouteRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTextToSpeechRouteRoute =
  DashboardTextToSpeechRouteRouteImport.update({
    id: '/text-to-speech',
    path: '/text-to-speech',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardVoicesIndexRoute = DashboardVoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardVoicesRouteRoute,
} as any)
const DashboardTextToSpeechIndexRoute =
  DashboardTextToSpeechIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardTextToSpeechRouteRoute,
  } as any)
const DashboardTextToSpeechGenerationIdRoute =
  DashboardTextToSpeechGenerationIdRouteImport.update({
    id: '/$generationId',
    path: '/$generationId',
    getParentRoute: () => DashboardTextToSpeechRouteRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/dashboard/text-to-speech': typeof DashboardTextToSpeechRouteRouteWithChildren
  '/dashboard/voices': typeof DashboardVoicesRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/text-to-speech/$generationId': typeof DashboardTextToSpeechGenerationIdRoute
  '/dashboard/text-to-speech/': typeof DashboardTextToSpeechIndexRoute
  '/dashboard/voices/': typeof DashboardVoicesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/text-to-speech/$generationId': typeof DashboardTextToSpeechGenerationIdRoute
  '/dashboard/text-to-speech': typeof DashboardTextToSpeechIndexRoute
  '/dashboard/voices': typeof DashboardVoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/success': typeof SuccessRoute
  '/dashboard/text-to-speech': typeof DashboardTextToSpeechRouteRouteWithChildren
  '/dashboard/voices': typeof DashboardVoicesRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/dashboard/text-to-speech/$generationId': typeof DashboardTextToSpeechGenerationIdRoute
  '/dashboard/text-to-speech/': typeof DashboardTextToSpeechIndexRoute
  '/dashboard/voices/': typeof DashboardVoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/success'
    | '/dashboard/text-to-speech'
    | '/dashboard/voices'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/text-to-speech/$generationId'
    | '/dashboard/text-to-speech/'
    | '/dashboard/voices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/success'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/text-to-speech/$generationId'
    | '/dashboard/text-to-speech'
    | '/dashboard/voices'
  id:
    | '__root__'
    | '/dashboard'
    | '/login'
    | '/success'
    | '/dashboard/text-to-speech'
    | '/dashboard/voices'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/dashboard/text-to-speech/$generationId'
    | '/dashboard/text-to-speech/'
    | '/dashboard/voices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuccessRoute: typeof SuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voices': {
      id: '/dashboard/voices'
      path: '/voices'
      fullPath: '/dashboard/voices'
      preLoaderRoute: typeof DashboardVoicesRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/text-to-speech': {
      id: '/dashboard/text-to-speech'
      path: '/text-to-speech'
      fullPath: '/dashboard/text-to-speech'
      preLoaderRoute: typeof DashboardTextToSpeechRouteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/voices/': {
      id: '/dashboard/voices/'
      path: '/'
      fullPath: '/dashboard/voices/'
      preLoaderRoute: typeof DashboardVoicesIndexRouteImport
      parentRoute: typeof DashboardVoicesRouteRoute
    }
    '/dashboard/text-to-speech/': {
      id: '/dashboard/text-to-speech/'
      path: '/'
      fullPath: '/dashboard/text-to-speech/'
      preLoaderRoute: typeof DashboardTextToSpeechIndexRouteImport
      parentRoute: typeof DashboardTextToSpeechRouteRoute
    }
    '/dashboard/text-to-speech/$generationId': {
      id: '/dashboard/text-to-speech/$generationId'
      path: '/$generationId'
      fullPath: '/dashboard/text-to-speech/$generationId'
      preLoaderRoute: typeof DashboardTextToSpeechGenerationIdRouteImport
      parentRoute: typeof DashboardTextToSpeechRouteRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardTextToSpeechRouteRouteChildren {
  DashboardTextToSpeechGenerationIdRoute: typeof DashboardTextToSpeechGenerationIdRoute
  DashboardTextToSpeechIndexRoute: typeof DashboardTextToSpeechIndexRoute
}

const DashboardTextToSpeechRouteRouteChildren: DashboardTextToSpeechRouteRouteChildren =
  {
    DashboardTextToSpeechGenerationIdRoute:
      DashboardTextToSpeechGenerationIdRoute,
    DashboardTextToSpeechIndexRoute: DashboardTextToSpeechIndexRoute,
  }

const DashboardTextToSpeechRouteRouteWithChildren =
  DashboardTextToSpeechRouteRoute._addFileChildren(
    DashboardTextToSpeechRouteRouteChildren,
  )

interface DashboardVoicesRouteRouteChildren {
  DashboardVoicesIndexRoute: typeof DashboardVoicesIndexRoute
}

const DashboardVoicesRouteRouteChildren: DashboardVoicesRouteRouteChildren = {
  DashboardVoicesIndexRoute: DashboardVoicesIndexRoute,
}

const DashboardVoicesRouteRouteWithChildren =
  DashboardVoicesRouteRoute._addFileChildren(DashboardVoicesRouteRouteChildren)

interface DashboardRouteChildren {
  DashboardTextToSpeechRouteRoute: typeof DashboardTextToSpeechRouteRouteWithChildren
  DashboardVoicesRouteRoute: typeof DashboardVoicesRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardTextToSpeechRouteRoute: DashboardTextToSpeechRouteRouteWithChildren,
  DashboardVoicesRouteRoute: DashboardVoicesRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SuccessRoute: SuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
